import random
from selenium import webdriver
import selenium
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.proxy import Proxy, ProxyType
import time


#proxy_ip = '27.71.80.199'
#proxy = Proxy()
#proxy.proxy_type = ProxyType.MANUAL
#proxy.http_proxy = proxy_ip
#proxy.ssl_proxy = proxy_ip

#capabilitites = webdriver.DesiredCapabilities.CHROME
#proxy.add_to_capabilities(capabilitites)

chrome_options = webdriver.ChromeOptions()
prefs = {"profile.default_content_setting_values.notifications" : 2}
chrome_options.add_experimental_option("prefs",prefs)
driver = webdriver.Chrome(chrome_options=chrome_options,#desired_capabilities=capabilitites
)
def __login__():
    driver.get('https://splinterlands.com/')
    driver.find_element_by_id('play_now_btn').click()
    time.sleep(2)
    driver.find_element_by_id('email').send_keys('danicarichardson1923@gmail.com')
    driver.find_element_by_id('password').send_keys('Zxcv123123')
    driver.find_element_by_id('password').send_keys(Keys.ENTER)
    time.sleep(2)
__login__()
def __setup__():
    driver.get('https://splinterlands.com/?p=battle_history')
    time.sleep(5)
    driver.get('https://splinterlands.com/?p=battle_history')
    time.sleep(5)
    driver.get('https://splinterlands.com/?p=battle_history')
    time.sleep(5)
    #driver.find_element_by_id('right_slider_btn').click()
    time.sleep(1)
    #driver.find_element_by_id('right_slider_btn').click()
    time.sleep(2)
__setup__()

def __play__():
    driver.find_element_by_id('battle_category_btn').click()
    time.sleep(10)
    driver.get('https://splinterlands.com/?p=create_team2')
    driver.set_window_size(width=1920,height=1080)
    time.sleep(10)
    driver.find_element_by_xpath('/html/body/div[3]/div/div/div/div[2]/div[3]/div[2]/button').click()
    time.sleep(10)
__play__()

def Malric_Inferno():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[1]/img').click()
def Pyre():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[2]/img').click()
def Alric_Stormbringer():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[3]/img').click()
def Lyanna_Natura():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[5]/img').click()
def Wizard_of_Eastwood():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[6]/img').click()
def Tyrus_Paladium():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[7]/img').click()
def Mother_Khala():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[8]/img').click()
def Zintar_Mortalis():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[9]/img').click()
def Contessa():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[10]/img').click()


########################################################################################

def Cerberus():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[11]/img').click()
def Serpentine_Spy():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[6]/img').click()
def Fire_Elemental():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[12]/img').click()
def Kobold_Miner():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[3]/img').click()
def Goblin_Chariot():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[27]/img').click()
def Cocatrice():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[23]/img').click()
def Fire_Beetle():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[4]/img').click()
def Kobold_Bruiser():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[5]/img').click()
def Living_Lava():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[13]/img').click()
def Magma_Troll():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[7]/img').click()
def Spark_Pixies():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[14]/img').click()
def Goblin_Shaman():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[1]/img').click()
def Elven_Cutthroat():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[17]/img').click()
def Serpentine_Soldier():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[9]/img').click()
def Tower_Griffin():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[28]/img').click()
def Centaur():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[18]/img').click()
def Goblin_Fireballer():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[8]/img').click()
def Elven_Mystic():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[26]/img').click()
def Elven_Defender():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[19]/img').click()

########################################################################################

def Cursed_Slimeball():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[6]/img').click()
def Haunted_Spirit():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[9]/img').click()
def Skeleton_Assassin():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[3]/img').click()
def Undead_Badger():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[8]/img').click()
def Undead_Priest():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[11]/img').click()
def Twisted_Jester():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[10]/img').click()
def Death_Elemental():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[14]/img').click()
def Bone_Golem():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[13]/img').click()
def Maggots():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[5]/img').click()
def Spineback_Wolf():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[4]/img').click()
def Mantoid():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[21]/img').click()
def Dark_Astronomer():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[12]/img').click()

###########################################################################################

def Stonesplitter_Orc():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[11]/img').click()
def Child_of_the_Forest():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[14]/img').click()
def Unicorn_Mustang():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[13]/img').click()
def Earth_Elemental():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[9]/img').click()
def Flesh_Golem():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[1]/img').click()
def Goblin_Sorcerer():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[2]/img').click()
def Rexxie():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[3]/img').click()
def Failed_Summoner():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[6]/img').click()
def Goblin_Thief():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[5]/img').click()
def Stone_Golem():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[10]/img').click()
def Minotaur_Warrior():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[4]/img').click()
def Khmer_Princess():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[12]/img').click()

#########################################################################################

def Silvershield_Paladin():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[10]/img').click()
def Divine_Healer():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[1]/img').click()
def Crystal_Jaguar():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[6]/img').click()
def Herbalist():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[8]/img').click()
def Lone_Boatman():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[7]/img').click()
def Peacebringer():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[9]/img').click()
def Clay_Golem():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[11]/img').click()
def Feral_Spirit():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[2]/img').click()
def Shieldbearer():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[14]/img').click()
def Enchanted_Pixie():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[25]/img').click()
def Luminous_Eagle():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[13]/img').click()
def Silvershield_Knight():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[3]/img').click()
def Cave_Slug():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[5]/img').click()
def Truthspeaker():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[12]/img').click()
########################################################################################

def Serpent_of_Eld():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[14]/img').click()
def Medusa():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[9]/img').click()
def Ice_Pixie():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[12]/img').click()
def Water_Elemental():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[10]/img').click()
def Frozen_Soldier():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[11]/img').click()
def Albatross():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[6]/img').click()
def Spineback_Turtle():
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div[4]/div[2]/img').click()

##############################################################
##############################################################
##############################################################
def select(s):
    if s == 12:
        m = random.randint(1,6)
        if m == 1:
            Zintar_Mortalis()
            time.sleep(2)
            Cursed_Slimeball()
            time.sleep(1)
            Haunted_Spirit()
            time.sleep(1)
            Skeleton_Assassin()
        if m == 2:
            Lyanna_Natura()
            time.sleep(2)
            Stonesplitter_Orc()
            time.sleep(1)
            Child_of_the_Forest()
        if m == 3:
            Malric_Inferno()
            time.sleep(2)
            Cerberus()
            time.sleep(1)
            Serpentine_Spy()
            time.sleep(1)
            Kobold_Miner()
        if m == 4:
            Tyrus_Paladium()
            time.sleep(2)
            Silvershield_Paladin()
            time.sleep(1)
            Divine_Healer()
        if m == 5:
            Malric_Inferno()
            time.sleep(2)
            Cerberus()
            time.sleep(1)
            Serpentine_Spy()
            time.sleep(1)
            Kobold_Miner()
        if m == 6:
            Alric_Stormbringer()
            time.sleep(2)
            Medusa()
            time.sleep(1)
            Ice_Pixie()
            time.sleep(1)
            Enchanted_Pixie()
    if s == 11:
        Zintar_Mortalis()
        time.sleep(2)
        Haunted_Spirit()
        time.sleep(1)
        Undead_Badger()
        time.sleep(1)
        Cursed_Slimeball()
    if s == 13:
        m = random.randint(1,5)
        if m == 1:
            Zintar_Mortalis()
            time.sleep(1)
            Haunted_Spirit()
            time.sleep(1)
            Undead_Badger()
            time.sleep(1)
            Skeleton_Assassin()
        if m == 2:
            Lyanna_Natura()
            time.sleep(2)
            Stonesplitter_Orc()
            time.sleep(1)
            Child_of_the_Forest()
        if m == 3:
            Malric_Inferno()
            time.sleep(2)
            Cerberus()
            time.sleep(1)
            Fire_Elemental()
        if m == 4:
            Tyrus_Paladium()
            time.sleep(2)
            Silvershield_Paladin()
            time.sleep(1)
            Divine_Healer()
        if m == 5:
            Alric_Stormbringer()
            time.sleep(2)
            Spineback_Turtle()
            time.sleep(1)
            Ice_Pixie()
            time.sleep(1)
            Medusa()
    if s == 14:
        m = random.randint(1,5)
        if m == 1:
            Zintar_Mortalis()
            time.sleep(2)
            Haunted_Spirit()
            time.sleep(1)
            Undead_Priest()
            time.sleep(1)
            Twisted_Jester()
        if m == 2:
            Wizard_of_Eastwood()
            time.sleep(2)
            Unicorn_Mustang()
            time.sleep(1)
            Earth_Elemental()
        if m == 3:
            Malric_Inferno()
            time.sleep(2)
            Cerberus()
            time.sleep(1)
            Goblin_Chariot()
            time.sleep(1)
            Cocatrice()
        if m == 4:
            Mother_Khala()
            time.sleep(2)
            Crystal_Jaguar()
            time.sleep(1)
            Herbalist()
            time.sleep(1)
            Lone_Boatman()
        if m == 5:
            Alric_Stormbringer()
            time.sleep(2)
            Frozen_Soldier()
            time.sleep(1)
            Water_Elemental()
    if s == 15:
        m = random.randint(1,5)
        if m == 1:
            Zintar_Mortalis()
            time.sleep(2)
            Haunted_Spirit()
            time.sleep(1)
            Twisted_Jester()
            time.sleep(1)
            Undead_Badger()
            time.sleep(1)
            Cursed_Slimeball()
        if m == 2:
            Lyanna_Natura()
            time.sleep(2)
            Flesh_Golem()
            time.sleep(1)
            Goblin_Sorcerer()
            time.sleep(1)
            Elven_Cutthroat()
        if m == 3:
            Malric_Inferno()
            time.sleep(2)
            Cerberus()
            time.sleep(1)
            Serpentine_Spy()
            time.sleep(1)
            Kobold_Miner()
            time.sleep(1)
            Fire_Beetle()
        if m == 4:
            Tyrus_Paladium()
            time.sleep(2)
            Silvershield_Paladin()
            time.sleep(1)
            Divine_Healer()
            time.sleep(1)
            Peacebringer()
        if m == 5:
            Alric_Stormbringer()
            time.sleep(2)
            Spineback_Turtle()
            time.sleep(1)
            Cocatrice()
            time.sleep(1)
            Ice_Pixie()
            time.sleep(1)
            Medusa()
    if s == 16:
        m = random.randint(1,5)
        if m == 1:
            Zintar_Mortalis()
            time.sleep(2)
            Haunted_Spirit()
            time.sleep(1)
            Undead_Priest()
            time.sleep(1)
            Undead_Badger()
            time.sleep(1)
            Twisted_Jester()
        if m == 2:
            Wizard_of_Eastwood()
            time.sleep(2)
            Rexxie()
            time.sleep(1)
            Tower_Griffin()
            time.sleep(1)
            Failed_Summoner()
        if m == 3:
            Pyre()
            time.sleep(2)
            Cerberus()
            time.sleep(1)
            Kobold_Bruiser()
            time.sleep(1)
            Serpentine_Spy()
            time.sleep(1)
            Fire_Beetle()
        if m == 4:
            Tyrus_Paladium()
            time.sleep(2)
            Clay_Golem()
            time.sleep(1)
            Divine_Healer()
            time.sleep(1)
            Peacebringer()
        if m == 5:
            Alric_Stormbringer()
            time.sleep(2)
            Serpent_of_Eld()
            time.sleep(1)
            Ice_Pixie()
            time.sleep(1)
            Medusa()
    if s == 17:
        m = random.randint(1,5)
        if m == 1:
            Zintar_Mortalis()
            time.sleep(2)
            Haunted_Spirit()
            time.sleep(1)
            Twisted_Jester()
            time.sleep(1)
            Undead_Badger()
            time.sleep(1)
            Undead_Priest()
            time.sleep(1)
            Cursed_Slimeball()
        if m == 2:
            Lyanna_Natura()
            time.sleep(2)
            Rexxie()
            time.sleep(1)
            Goblin_Thief()
            time.sleep(1)
            Earth_Elemental()
        if m == 3:
            Pyre()
            time.sleep(2)
            Cocatrice()
            time.sleep(1)
            Cerberus()
            time.sleep(1)
            Fire_Beetle()
            time.sleep(1)
            Serpentine_Spy()
            time.sleep(1)
            Kobold_Miner()
        if m == 4:
            Mother_Khala()
            time.sleep(2)
            Crystal_Jaguar()
            time.sleep(1)
            Feral_Spirit()
            time.sleep(1)
            Divine_Healer()
            time.sleep(1)
            Peacebringer()
        if m == 5:
            Alric_Stormbringer()
            time.sleep(2)
            Frozen_Soldier()
            time.sleep(1)
            Medusa()
            time.sleep(1)
            Elven_Mystic()
    if s == 18:
        m = random.randint(1,5)
        if m == 1:
            Zintar_Mortalis()
            time.sleep(2)
            Haunted_Spirit()
            time.sleep(1)
            Undead_Priest()
            time.sleep(1)
            Skeleton_Assassin()
            time.sleep(1)
            Twisted_Jester()
            time.sleep(1)
            Cursed_Slimeball()
        if m == 2:
            Lyanna_Natura()
            time.sleep(2)
            Rexxie()
            time.sleep(1)
            Goblin_Thief()
            time.sleep(1)
            Earth_Elemental()
        if m == 3:
            Malric_Inferno()
            time.sleep(2)
            Living_Lava()
            time.sleep(1)
            Magma_Troll()
            time.sleep(1)
            Cerberus()
        if m == 4:
            Tyrus_Paladium()
            time.sleep(2)
            Silvershield_Paladin()
            time.sleep(1)
            Divine_Healer()
            time.sleep(1)
            Feral_Spirit()
            time.sleep(1)
            Peacebringer()
        if m == 5:
            Alric_Stormbringer()
            time.sleep(2)
            Serpent_of_Eld()
            time.sleep(1)
            Water_Elemental()
            time.sleep(1)
            Water_Elemental()
            time.sleep(1)
            Albatross()
    if s == 19:
        m = random.randint(1,5)
        if m == 1:
            Zintar_Mortalis()
            time.sleep(2)
            Haunted_Spirit()
            time.sleep(1)
            Skeleton_Assassin()
            time.sleep(1)
            Undead_Badger()
            time.sleep(1)
            Twisted_Jester()
            time.sleep(1)
            Undead_Priest()
        if m == 2:
            Lyanna_Natura()
            time.sleep(2)
            Stone_Golem()
            time.sleep(1)
            Goblin_Thief()
            time.sleep(1)
            Goblin_Sorcerer()
            time.sleep(1)
            Centaur()
        if m == 3:
            Malric_Inferno()
            time.sleep(2)
            Cerberus()
            time.sleep(1)
            Kobold_Bruiser()
            time.sleep(1)
            Serpentine_Spy()
            time.sleep(1)
            Kobold_Miner()
            time.sleep(1)
            Spark_Pixies()
        if m == 4:
            Tyrus_Paladium()
            time.sleep(2)
            Silvershield_Paladin()
            time.sleep(1)
            Divine_Healer()
            time.sleep(1)
            Feral_Spirit()
            time.sleep(1)
            Peacebringer()
        if m == 5:
            Alric_Stormbringer()
            time.sleep(2)
            Frozen_Soldier()
            time.sleep(1)
            Medusa()
            time.sleep(1)
            Ice_Pixie()
            time.sleep(1)
            Elven_Mystic()
    if s == 20:
        m = random.randint(1,5)
        if m == 1:
            Zintar_Mortalis()
            time.sleep(2)
            Haunted_Spirit()
            time.sleep(1)
            Undead_Priest()
            time.sleep(1)
            Skeleton_Assassin()
            time.sleep(1)
            Death_Elemental()
            time.sleep(1)
            Twisted_Jester()
        if m == 2:
            Lyanna_Natura()
            time.sleep(2)
            Failed_Summoner()
            time.sleep(1)
            Stone_Golem()
            Goblin_Thief()
            time.sleep(1)
            Child_of_the_Forest()
            time.sleep(1)
            Goblin_Sorcerer()
        if m == 3:
            Malric_Inferno()
            time.sleep(2)
            Cerberus()
            time.sleep(1)
            Fire_Beetle()
            time.sleep(1)
            Goblin_Shaman()
            time.sleep(1)
            Serpentine_Spy()
            time.sleep(1)
            Spark_Pixies()
        if m == 4:
            Tyrus_Paladium()
            time.sleep(2)
            Silvershield_Paladin()
            time.sleep(1)
            Divine_Healer()
            time.sleep(1)
            Feral_Spirit()
            time.sleep(1)
            Peacebringer()
        if m == 5:
            Alric_Stormbringer()
            time.sleep(2)
            Water_Elemental()
            time.sleep(1)
            Medusa()
            time.sleep(1)
            Ice_Pixie()
            time.sleep(1)
            Enchanted_Pixie()
            time.sleep(1)
            Cocatrice()
            time.sleep(1)
            Albatross()
    if s == 21:
        m = random.randint(1,5)
        if m == 1:
            Zintar_Mortalis()
            time.sleep(2)
            Cocatrice()
            time.sleep(1)
            Haunted_Spirit()
            time.sleep(1)
            Twisted_Jester()
            time.sleep(1)
            Undead_Priest()
            time.sleep(1)
            Undead_Badger()
            time.sleep(1)
            Skeleton_Assassin()
        if m == 2:
            Lyanna_Natura()
            time.sleep(2)
            Unicorn_Mustang()
            time.sleep(1)
            Goblin_Thief
            time.sleep(1)
            Goblin_Sorcerer()
            time.sleep(1)
            Earth_Elemental()
        if m == 3:
            Malric_Inferno()
            time.sleep(2)
            Living_Lava()
            time.sleep(1)
            Goblin_Shaman()
            time.sleep(1)
            Elven_Cutthroat()
            time.sleep(1)
            Serpentine_Spy()
            time.sleep(1)
            Kobold_Miner()
        if m == 4:
            Mother_Khala()
            time.sleep(2)
            Shieldbearer()
            time.sleep(1)
            Divine_Healer()
            time.sleep(1)
            Peacebringer()
            time.sleep(1)
            Enchanted_Pixie()
        if m == 5:
            Alric_Stormbringer()
            time.sleep(2)
            Serpent_of_Eld()
            time.sleep(1)
            Medusa()
            time.sleep(1)
            Ice_Pixie()
            time.sleep(1)
            Water_Elemental()
    if s == 22:
        m = random.randint(1,5)
        if m == 1:
            Contessa()
            time.sleep(2)
            Haunted_Spirit()
            time.sleep(1)
            Skeleton_Assassin()
            time.sleep(1)
            Death_Elemental()
            time.sleep(1)
            Undead_Priest()
            time.sleep(1)
            Twisted_Jester()
            time.sleep(1)
            Undead_Badger()
        if m == 2:
            Lyanna_Natura()
            time.sleep(2)
            Unicorn_Mustang()
            time.sleep(1)
            Minotaur_Warrior()
            time.sleep(1)
            Goblin_Thief()
            time.sleep(1)
            Goblin_Sorcerer()
        if m == 3:
            Malric_Inferno()
            time.sleep(2)
            Serpentine_Soldier()
            time.sleep(1)
            Serpentine_Spy()
            time.sleep(1)
            Fire_Beetle()
            time.sleep(1)
            Kobold_Miner()
            time.sleep(1)
            Elven_Cutthroat()
            time.sleep(1)
            Goblin_Shaman()
        if m == 4:
            Tyrus_Paladium()
            time.sleep(1)
            Clay_Golem()
            time.sleep(1)
            Peacebringer()
            time.sleep(1)
            Divine_Healer()
            time.sleep(1)
            Enchanted_Pixie()
            time.sleep(1)
            Feral_Spirit()
        if m == 5:
            Alric_Stormbringer()
            time.sleep(2)
            Frozen_Soldier()
            time.sleep(1)
            Elven_Mystic()
            time.sleep(1)
            Enchanted_Pixie()
            time.sleep(1)
            Ice_Pixie()
            time.sleep(1)
            Medusa()
    if s == 23:
        m = random.randint(1,5)
        if m == 1:
            Zintar_Mortalis()
            time.sleep(2)
            Bone_Golem()
            time.sleep(1)
            Haunted_Spirit()
            time.sleep(1)
            Maggots()
            time.sleep(1)
            Undead_Badger()
            time.sleep(1)
            Death_Elemental()
        if m == 2:
            Lyanna_Natura()
            time.sleep(2)
            Unicorn_Mustang()
            time.sleep(1)
            Goblin_Sorcerer()
            time.sleep(1)
            Goblin_Thief()
            time.sleep(1)
            Khmer_Princess()
            time.sleep(1)
            Earth_Elemental()
        if m == 3:
            Malric_Inferno()
            time.sleep(2)
            Living_Lava()
            time.sleep(1)
            Cerberus()
            time.sleep(1)
            Fire_Elemental()
            time.sleep(1)
            Serpentine_Spy()
        if m == 4:
            Mother_Khala()
            time.sleep(2)
            Shieldbearer()
            time.sleep(1)
            Peacebringer()
            time.sleep(1)
            Divine_Healer()
            time.sleep(1)
            Feral_Spirit()
            time.sleep(1)
            Herbalist()
        if m == 5:
            Alric_Stormbringer()
            time.sleep(2)
            Serpent_of_Eld()
            time.sleep(1)
            Medusa()
            time.sleep(1)
            Ice_Pixie()
            time.sleep(1)
            Enchanted_Pixie()
            time.sleep(1)
            Elven_Mystic()
    if s == 24:
        m = random.randint(1,5)
        if m == 1:
            Zintar_Mortalis()
            time.sleep(2)
            Haunted_Spirit()
            time.sleep(1)
            Spineback_Wolf()
            time.sleep(1)
            Skeleton_Assassin()
            time.sleep(1)
            Undead_Badger()
            time.sleep(1)
            Twisted_Jester()
            time.sleep(1)
            Undead_Priest()
        if m == 2:
            Lyanna_Natura()
            time.sleep(2)
            Unicorn_Mustang()
            time.sleep(1)
            Stonesplitter_Orc()
            time.sleep(1)
            Child_of_the_Forest()
            time.sleep(1)
            Khmer_Princess()
            time.sleep(1)
            Khmer_Princess()
            time.sleep(1)
            Failed_Summoner()
        if m == 3:
            Malric_Inferno()
            time.sleep(2)
            Cerberus()
            time.sleep(1)
            Serpentine_Spy()
            time.sleep(1)
            Kobold_Miner()
            time.sleep(1)
            Fire_Elemental()
            time.sleep(1)
            Goblin_Shaman()
            time.sleep(1)
            Tower_Griffin()
        if m == 4:
            Mother_Khala()
            time.sleep(2)
            Shieldbearer()
            time.sleep(1)
            Peacebringer()
            time.sleep(1)
            Divine_Healer()
            time.sleep(1)
            Feral_Spirit()
            time.sleep(1)
            Herbalist()
        if m == 5:
            Alric_Stormbringer()
            time.sleep(2)
            Frozen_Soldier()
            time.sleep(1)
            Water_Elemental()
            time.sleep(1)
            Medusa()
            time.sleep(1)
            Ice_Pixie()
            time.sleep(1)
            Elven_Mystic()
    if s == 25:
        m = random.randint(1,5)
        if m == 1:
            Zintar_Mortalis()
            time.sleep(2)
            Haunted_Spirit()
            time.sleep(1)
            Undead_Priest()
            time.sleep(1)
            Skeleton_Assassin()
            time.sleep(1)
            Undead_Badger()
            time.sleep(1)
            Twisted_Jester()
            time.sleep(1)
            Mantoid()
        if m == 2:
            Lyanna_Natura()
            time.sleep(2)
            Elven_Defender()
            time.sleep(1)
            Failed_Summoner()
            time.sleep(1)
            Child_of_the_Forest()
            time.sleep(1)
            Goblin_Thief()
            time.sleep(1)
            Khmer_Princess()
            time.sleep(1)
            Earth_Elemental()
        if m == 3:
            Malric_Inferno()
            time.sleep(2)
            Living_Lava()
            time.sleep(1)
            Fire_Elemental()
            time.sleep(1)
            Serpentine_Spy()
            time.sleep(1)
            Spark_Pixies()
            time.sleep(1)
            Fire_Beetle()
        if m == 4:
            Mother_Khala()
            time.sleep(2)
            Shieldbearer()
            time.sleep(1)
            Luminous_Eagle()
            time.sleep(1)
            Divine_Healer()
            time.sleep(1)
            Peacebringer()
        if m == 5:
            Alric_Stormbringer()
            time.sleep(2)
            Serpent_of_Eld()
            time.sleep(1)
            Water_Elemental()
            time.sleep(1)
            Medusa()
            time.sleep(1)
            Ice_Pixie()
            time.sleep(1)
            Elven_Mystic()
    if s == 26:
        m = random.randint(1,5)
        if m == 1:
            Zintar_Mortalis()
            time.sleep(2)
            Haunted_Spirit()
            time.sleep(1)
            Twisted_Jester()
            time.sleep(1)
            Undead_Priest()
            time.sleep(1)
            Dark_Astronomer()
            time.sleep(1)
            Skeleton_Assassin()
            time.sleep(1)
            Spineback_Wolf()
        if m == 2:
            Lyanna_Natura()
            time.sleep(2)
            Unicorn_Mustang()
            time.sleep(1)
            Failed_Summoner()
            time.sleep(1)
            Khmer_Princess()
            time.sleep(1)
            Goblin_Thief()
            time.sleep(1)
            Child_of_the_Forest()
            time.sleep(1)
            Earth_Elemental()
        if m == 3:
            Pyre()
            time.sleep(2)
            Cerberus()
            time.sleep(1)
            Magma_Troll()
            time.sleep(1)
            Serpentine_Spy()
            time.sleep(1)
            Fire_Elemental()
            time.sleep(1)
            Fire_Beetle()
            time.sleep(1)
            Centaur()
        if m == 4:
            Tyrus_Paladium()
            time.sleep(2)
            Silvershield_Paladin()
            time.sleep(1)
            Silvershield_Knight()
            time.sleep(1)
            Feral_Spirit()
            time.sleep(1)
            Elven_Cutthroat()
            time.sleep(1)
            Divine_Healer()
            time.sleep(1)
            Cocatrice()
            time.sleep(1)
        if m == 5:
            Alric_Stormbringer()
            time.sleep(2)
            Serpent_of_Eld()
            time.sleep(1)
            Water_Elemental()
            time.sleep(1)
            Medusa()
            time.sleep(1)
            Ice_Pixie()
            time.sleep(1)
            Elven_Mystic()
            time.sleep(1)
            Albatross()
    if s == 27:
        m = random.randint(1,3)
        if m == 1:
            Zintar_Mortalis()
            time.sleep(2)
            Bone_Golem()
            time.sleep(1)
            Haunted_Spirit()
            time.sleep(1)
            Death_Elemental()
            time.sleep(1)
            Skeleton_Assassin()
            time.sleep(1)
            Twisted_Jester()
            time.sleep(1)
            Undead_Badger()
        if m == 2:
            Lyanna_Natura()
            time.sleep(2)
            Unicorn_Mustang()
            time.sleep(1)
            Earth_Elemental()
            time.sleep(1)
            Goblin_Thief()
            time.sleep(1)
            Goblin_Sorcerer()
            time.sleep(1)
            Child_of_the_Forest()
            time.sleep(1)
            Elven_Cutthroat()
        if m == 3:
            Malric_Inferno()
            time.sleep(2)
            Living_Lava()
            time.sleep(1)
            Fire_Elemental()
            time.sleep(1)
            Serpentine_Spy()
            time.sleep(1)
            Spark_Pixies()
            time.sleep(1)
            Kobold_Bruiser()
            time.sleep(1)
            Goblin_Fireballer()
    if s == 28:
        m = random.randint(1,3)
        if m == 1:
            Zintar_Mortalis()
            time.sleep(2)
            Haunted_Spirit()
            time.sleep(1)
            Skeleton_Assassin()
            time.sleep(1)
            Undead_Priest()
            time.sleep(1)
            Death_Elemental()
            time.sleep(1)
            Twisted_Jester()
            time.sleep(1)
            Mantoid()
        if m == 2:
            Lyanna_Natura()
            time.sleep(2)
            Unicorn_Mustang()
            time.sleep(1)
            Earth_Elemental()
            time.sleep(1)
            Goblin_Thief()
            time.sleep(1)
            Goblin_Sorcerer()
            time.sleep(1)
            Child_of_the_Forest()
            time.sleep(1)
            Elven_Cutthroat()
        if m == 3:
            Pyre()
            time.sleep(2)
            Living_Lava()
            time.sleep(1)
            Cerberus()
            time.sleep(1)
            Fire_Beetle()
            time.sleep(1)
            Serpentine_Spy()
            time.sleep(1)
            Spark_Pixies()
            time.sleep(1)
            Elven_Mystic()
    if s == 29:
        m = random.randint(1,3)
        if m == 1:
            Zintar_Mortalis()
            time.sleep(2)
            Bone_Golem()
            time.sleep(1)
            Haunted_Spirit()
            time.sleep(1)
            Skeleton_Assassin()
            time.sleep(1)
            Mantoid()
            time.sleep(1)
            Undead_Badger()
            time.sleep(1)
            Undead_Priest()
        if m == 2:
            Lyanna_Natura()
            time.sleep(2)
            Unicorn_Mustang()
            time.sleep(1)
            Goblin_Thief()
            time.sleep(1)
            Goblin_Sorcerer()
            time.sleep(1)
            Elven_Cutthroat()
            time.sleep(1)
            Khmer_Princess()
            time.sleep(1)
            Mantoid()
        if m == 3:
            Pyre()
            time.sleep(2)
            Elven_Defender()
            time.sleep(1)
            Cerberus()
            time.sleep(1)
            Serpentine_Spy()
            time.sleep(1)
            Fire_Elemental()
            time.sleep(1)
            Spark_Pixies()
            time.sleep(1)
            Kobold_Miner()
    if s == 30:
        m = random.randint(1,3)
        if m == 1:
            Zintar_Mortalis()
            time.sleep(2)
            Haunted_Spirit()
            time.sleep(1)
            Bone_Golem()
            time.sleep(1)
            Undead_Priest()
            time.sleep(1)
            Death_Elemental()
            time.sleep(1)
            Twisted_Jester()
            time.sleep(1)
            Mantoid()
        if m == 2:
            Lyanna_Natura()
            time.sleep(2)
            Unicorn_Mustang()
            time.sleep(1)
            Goblin_Thief()
            time.sleep(1)
            Goblin_Sorcerer()
            time.sleep(1)
            Elven_Cutthroat()
            time.sleep(1)
            Khmer_Princess()
            time.sleep(1)
            Mantoid()
        if m == 3:
            Pyre()
            time.sleep(2)
            Elven_Defender()
            time.sleep(1)
            Cerberus()
            time.sleep(1)
            Serpentine_Spy()
            time.sleep(1)
            Fire_Elemental()
            time.sleep(1)
            Spark_Pixies()
            time.sleep(1)
            Fire_Beetle()
    if s == 31:
        m = random.randint(1,3)
        if m == 1:
            Zintar_Mortalis()
            time.sleep(2)
            Haunted_Spirit()
            time.sleep(1)
            Bone_Golem()
            time.sleep(1)
            Undead_Priest()
            time.sleep(1)
            Death_Elemental()
            time.sleep(1)
            Twisted_Jester()
            time.sleep(1)
            Mantoid()
        if m == 2:
            Lyanna_Natura()
            time.sleep(2)
            Unicorn_Mustang()
            time.sleep(1)
            Goblin_Thief()
            time.sleep(1)
            Goblin_Sorcerer()
            time.sleep(1)
            Elven_Cutthroat()
            time.sleep(1)
            Khmer_Princess()
            time.sleep(1)
            Mantoid()
        if m == 3:
            Pyre()
            time.sleep(2)
            Elven_Defender()
            time.sleep(1)
            Cerberus()
            time.sleep(1)
            Serpentine_Spy()
            time.sleep(1)
            Fire_Elemental()
            time.sleep(1)
            Spark_Pixies()
            time.sleep(1)
            Fire_Beetle()
    if s >= 32:
        m = random.randint()
        if m == 1:
            Zintar_Mortalis()
            time.sleep(2)
            Haunted_Spirit()
            time.sleep(1)
            Bone_Golem()
            time.sleep(1)
            Undead_Priest()
            time.sleep(1)
            Death_Elemental()
            time.sleep(1)
            Twisted_Jester()
            time.sleep(1)
            Mantoid()
        if m == 2:
            Lyanna_Natura()
            time.sleep(2)
            Unicorn_Mustang()
            time.sleep(1)
            Goblin_Thief()
            time.sleep(1)
            Goblin_Sorcerer()
            time.sleep(1)
            Elven_Cutthroat()
            time.sleep(1)
            Khmer_Princess()
            time.sleep(1)
            Mantoid()
        if m == 3:
            Malric_Inferno()
            time.sleep(2)
            Living_Lava()
            time.sleep(1)
            Cerberus()
            time.sleep(1)
            Serpentine_Spy()
            time.sleep(1)
            Fire_Elemental()
            time.sleep(1)
            Spark_Pixies()
            time.sleep(1)
            Elven_Mystic()

